config/routes.rb
CompMS::Application.routes.draw do
  resources :competencies

  get "home/index"

  root :to => 'home#index'

end

app/models/competency.rb
class Competency < ActiveRecord::Base
  attr_accessible :description, :name
  
  validates :name, :presence => true
  validates :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/competencies_controller.rb
class CompetenciesController < ApplicationController
  # GET /competencies
  # GET /competencies.json
  def index
    @competencies = Competency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competencies }
    end
  end

  # GET /competencies/1
  # GET /competencies/1.json
  def show
    @competency = Competency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competency }
    end
  end

  # GET /competencies/new
  # GET /competencies/new.json
  def new
    @competency = Competency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competency }
    end
  end

  # GET /competencies/1/edit
  def edit
    @competency = Competency.find(params[:id])
  end

  # POST /competencies
  # POST /competencies.json
  def create
    @competency = Competency.new(params[:competency])

    respond_to do |format|
      if @competency.save
        format.html { redirect_to @competency, notice: 'Competency was successfully created.' }
        format.json { render json: @competency, status: :created, location: @competency }
      else
        format.html { render action: "new" }
        format.json { render json: @competency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competencies/1
  # PUT /competencies/1.json
  def update
    @competency = Competency.find(params[:id])

    respond_to do |format|
      if @competency.update_attributes(params[:competency])
        format.html { redirect_to @competency, notice: 'Competency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competencies/1
  # DELETE /competencies/1.json
  def destroy
    @competency = Competency.find(params[:id])
    @competency.destroy

    respond_to do |format|
      format.html { redirect_to competencies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competencies_helper.rb
module CompetenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/competencies/_form.html.erb
<%= form_for(@competency) do |f| %>
  <% if @competency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competency.errors.count, "error") %> prohibited this competency from being saved:</h2>

      <ul>
      <% @competency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competencies/edit.html.erb
<h1>Editing competency</h1>

<%= render 'form' %>

<%= link_to 'Show', @competency %> |
<%= link_to 'Back', competencies_path %>

app/views/competencies/index.html.erb
<h1>Listing competencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @competencies.each do |competency| %>
  <tr>
    <td><%= competency.name %></td>
    <td><%= competency.description %></td>
    <td><%= link_to 'Show', competency %></td>
    <td><%= link_to 'Edit', edit_competency_path(competency) %></td>
    <td><%= link_to 'Destroy', competency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Competency', new_competency_path %>

app/views/competencies/new.html.erb
<h1>New competency</h1>

<%= render 'form' %>

<%= link_to 'Back', competencies_path %>

app/views/competencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @competency.name %>
</p>

<p>
  <b>Description:</b>
  <%= @competency.description %>
</p>


<%= link_to 'Edit', edit_competency_path(@competency) %> |
<%= link_to 'Back', competencies_path %>

app/views/home/index.html.erb
<h1>Hello on CompMS</h1>
<%= link_to "Competencies", competencies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompMS</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>